apiVersion: integration/v1
kind: Step
name: stack-deploy
version: 4
summary: Deploy CloudFormation stack
description: Runs a CloudFormation deploy to create or update a stack contained in a Git repository.

icon:

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/aws-cloudformation-step-stack-deploy

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json

examples:
- summary: "Deploy a CloudFormation stack"
  content:
    apiVersion: v1
    kind: Step
    name: cloudformation-deployer
    image: relaysh/aws-cloudformation-step-stack-deploy
    spec:
      aws:
        connection: ${connections.aws.my-aws-connection}
        region: ${parameters.awsRegion}
      stackName: ${parameters.stackName}
      templateFile: templates/template.yaml
      git:
        connection: ${connections.ssh.my-github-ssh-connection}
        repository: ${parameters.repository}
        name: ${parameters.repositoryName}
        branch: ${parameters.branch}
      parameters:
        Environment: ${parameters.environment}
        CertificateARN: ${parameters.certificateARN}
      s3:
        bucket: ${parameters.bucketName}
        prefix: ${parameters.bucketPrefix}
      capabilities:
        - CAPABILITY_NAMED_IAM
